### ISSUE TITLE
Send sendpoints reason length error in whispers

### ISSUE THREAD

**Issue by Marenthyu** [Marenthyu/NepBot#114]
https://github.com/Marenthyu/NepBot/blob/8db0b4396d4fbdd0ae83bddd2b3877d856f53222/main.py#L5991

derp. needs to pass isWhisper

**Comment by Marenthyu** [comment]
same for the ultimate confirmation response.

**Comment by Dabomstew** [comment]
Agreed, though I question this being an issue instead of just a PR 👀

**Comment by Marenthyu** [comment]
I was on my way to bed when i noticed

**Comment by Marenthyu** [comment]
Closed by #115
