### ISSUE TITLE
change !freewaifu pack text 

### ISSUE THREAD

**Issue by Honbuk** [Marenthyu/NepBot#45]
Make it so it says "user, you redeemed your daily freewaifu pack and you get: Booster link"

Currently it shows "user, you dropped a new waifu: [ID][Rarity] Waifu from Series - Picture ( Booster link )"

In my opinion, the freewaifu information is not needed when you take it as pack, because you will see it anyways when you click the pack.

**Comment by Dabomstew** [comment]
You're not wrong, but that implies that they actually click the pack link, which adds an extra step. To me, the pack link is only provided out of courtesy / to solidify the fact that this counts as a pack. Most people will just be trashing immediately which would force them to actually look at the pack first.

**Comment by Marenthyu** [comment]
I would then remove the image link from the pack freewaifu to considerably reduce the amount of spam/text, as it takes a lot of space

**Comment by Dabomstew** [comment]
This seems like a reasonable compromise.
