### ISSUE TITLE
button to switch between hand and set list

### ISSUE THREAD

**Issue by wherewedroppinboys** [Marenthyu/NepBot#47]
![image](https://user-images.githubusercontent.com/8564567/40964014-44367dc6-6867-11e8-9307-d8a5c52cb7aa.png)

ez example, a one click button instead of having to navigate via URL bar would be bomb af because i'm lazy and it'd be a huge QoL thing for moron set hunters like me and also everyone else at the same time

points to zfresh for mentioning to maren that this was an idea
points to maren for showing me how to github

**Comment by wherewedroppinboys** [comment]
![image](https://user-images.githubusercontent.com/8564567/40964337-1aa736d4-6868-11e8-979f-52d49b791bc5.png)
 

new mockup of base set page as hand/profile/etc would be useful too, optionally grey out view booster if there isn't an open one? 

additionally, open booster could appear between/below any of these if there's an available one, which would remove a button entirely

**Comment by Marenthyu** [comment]
I would want to stay consistent with the button placement and hence place them at the top as with /profile

Greying out/removing the booster button would require an additional query and so i would not want to have that.

Maybe make it a dropdown button saying "Go to..." - would add another click to navigating, but as a usability vs UI tradeoff i think it's ok.

**Comment by Honbuk** [comment]
Would add another click, but definitely easier and faster than typing the url. That's fine I think.

**Comment by wherewedroppinboys** [comment]
dropdown would work fine imho as long as it doesn't overlap the set buttons and look super wonky tbh, one click isn't that bad compared to manually entering a URL to check someone's hand

**Comment by wherewedroppinboys** [comment]
example i guess kek may as well remain consistent
![image](https://user-images.githubusercontent.com/8564567/40966468-ce6b4c50-686d-11e8-879c-9c37aef94186.png)
