### ISSUE TITLE
trade: godimage request cancellation message is apparently always whispered on God trade

### ISSUE THREAD

**Issue by xorhash** [Marenthyu/NepBot#69]
The `!trade` command is supposed to whisper "Your image change request for [%d] %s was cancelled since you traded it away." if and only if a request was actually cancelled.

Honbuk apparently encountered that the message always gets whispered. Supposedly, the image change has already been approved a while ago, no new one was pending. I.e., the state of the card *should* have been: God image change requested, then approved.

The code looks correct at a glance, I wonder why `cur.rowcount` misbehaved. The debug logs may likely help. The card in question was ID 127, held by Honbuk until it was traded today.

**Comment by Dabomstew** [comment]
There *was* a new one pending. Honbuk requested another image change on August 6, we didn't accept it or deny it yet since we wanted to set some kind of informal rule about repeated requests in a short span of time.
